version: "3.7"
services:
  gpconnect-db:
    image: mariadb
    networks: 
      - gpconnect-network
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=gpconnectdbuser
      - MYSQL_PASSWORD=gpc0nn3ct
      - MYSQL_DATABASE=gpconnect
  gpconnect-api:
    build:
      target: runtime
      context: .
      dockerfile: Dockerfile-api
    command: java -jar /app/app.war
    ports:
      - 9000:19191
      - 9001:19192
    networks: 
      - gpconnect-network
    environment:
      - DATABASE_ADDRESS=gpconnect-db
      - DATABASE_USERNAME=gpconnectdbuser
      - DATABASE_PASSWORD=gpc0nn3ct
      - DATABASE_SCHEMA=gpconnect
      - SERVER_BASE_URL=https://data.developer.nhs.uk/gpconnect-demonstrator/v1/fhir
      - CONTEXT_PATH=/gpconnect-demonstrator/v1/
    links:
      - gpconnect-db
    depends_on:
      - gpconnect-db

networks: 
  gpconnect-network:
    driver: bridge
