version: "3"
services:
  gpconnect-db:
    image: mysql
    networks: 
      - gpconnect-network
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: answer
      MYSQL_PASSWORD: answer99q
      MYSQL_DATABASE: gpconnect
      MYSQL_PORT: 3306
  gpconnect-api:
    image: gpconnect # rename to whatever you tagged the GP Connect build is
    ports:
      - 9000:19191
      - 9001:19192
    networks: 
      - gpconnect-network
    environment:
      - DATABASE_ADDRESS=gpconnect-db
      - DATABASE_PORT=3306
    links:
      - gpconnect-db
    depends_on:
      - gpconnect-db

networks: 
  gpconnect-network:
    driver: bridge
